import { Course, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Development', icon: 'Code', courses_count: 1240 },
  { id: '2', name: 'Business', icon: 'Briefcase', courses_count: 850 },
  { id: '3', name: 'Design', icon: 'Palette', courses_count: 620 },
  { id: '4', name: 'Marketing', icon: 'Megaphone', courses_count: 430 },
  { id: '5', name: 'IT & Software', icon: 'Cpu', courses_count: 910 },
  { id: '6', name: 'Personal Development', icon: 'User', courses_count: 540 },
];

export const MOCK_COURSES: Course[] = [
  {
    id: 'c1',
    title: 'Complete Web Design from Figma to Webflow',
    description: 'Learn how to design beautiful websites in Figma and build them in Webflow without coding.',
    instructor: 'Vako Shvili',
    instructor_id: 'i1',
    price: 19.99,
    old_price: 84.99,
    rating: 4.8,
    reviews_count: 12540,
    thumbnail: 'https://picsum.photos/seed/webdesign/800/450',
    category: 'Design',
    level: 'Beginner',
    duration: '22.5 hours',
    lessons_count: 145,
    updated_at: '2024-02-15',
    is_bestseller: true,
  },
  {
    id: 'c2',
    title: 'The Complete 2024 Web Development Bootcamp',
    description: 'Become a Full-Stack Web Developer with just ONE course. HTML, CSS, Javascript, Node, React, PostgreSQL, Web3 and DApps.',
    instructor: 'Dr. Angela Yu',
    instructor_id: 'i2',
    price: 14.99,
    old_price: 74.99,
    rating: 4.9,
    reviews_count: 352100,
    thumbnail: 'https://picsum.photos/seed/webdev/800/450',
    category: 'Development',
    level: 'All Levels',
    duration: '65 hours',
    lessons_count: 450,
    updated_at: '2024-01-10',
    is_bestseller: true,
  },
  {
    id: 'c3',
    title: 'Machine Learning A-Z™: AI, Python & R',
    description: 'Learn to create Machine Learning Algorithms in Python and R from two Data Science experts. Code templates included.',
    instructor: 'Kirill Eremenko',
    instructor_id: 'i3',
    price: 12.99,
    old_price: 94.99,
    rating: 4.6,
    reviews_count: 165400,
    thumbnail: 'https://picsum.photos/seed/ai/800/450',
    category: 'Development',
    level: 'Intermediate',
    duration: '42 hours',
    lessons_count: 280,
    updated_at: '2023-12-05',
  },
  {
    id: 'c4',
    title: 'Ultimate AWS Certified Solutions Architect Associate',
    description: 'Pass the AWS Certified Solutions Architect Associate Certification SAA-C03. Full practice exam included.',
    instructor: 'Stephane Maarek',
    instructor_id: 'i4',
    price: 15.99,
    old_price: 89.99,
    rating: 4.7,
    reviews_count: 210500,
    thumbnail: 'https://picsum.photos/seed/aws/800/450',
    category: 'IT & Software',
    level: 'Intermediate',
    duration: '27 hours',
    lessons_count: 390,
    updated_at: '2024-02-28',
    is_bestseller: true,
  },
  {
    id: 'c5',
    title: 'Digital Marketing Masterclass - 23 Courses in 1',
    description: 'Social Media Marketing, SEO, YouTube, Email, Facebook Marketing, Google Analytics and more!',
    instructor: 'Phil Ebiner',
    instructor_id: 'i5',
    price: 11.99,
    old_price: 99.99,
    rating: 4.5,
    reviews_count: 85400,
    thumbnail: 'https://picsum.photos/seed/marketing/800/450',
    category: 'Marketing',
    level: 'All Levels',
    duration: '32.5 hours',
    lessons_count: 210,
    updated_at: '2024-01-20',
  },
  {
    id: 'c6',
    title: 'Financial Analysis and Investing Masterclass',
    description: 'Learn professional financial analysis, stock market investing, and portfolio management.',
    instructor: 'Mohsen Hassan',
    instructor_id: 'i6',
    price: 13.99,
    old_price: 79.99,
    rating: 4.7,
    reviews_count: 42100,
    thumbnail: 'https://picsum.photos/seed/finance/800/450',
    category: 'Business',
    level: 'Intermediate',
    duration: '18 hours',
    lessons_count: 120,
    updated_at: '2024-03-01',
  }
];
